emit:
  - "@typespec/openapi3"

output-dir: "{project-root}/tmp/typespec"

options:
  "@typespec/openapi3":
    emitter-output-dir: "{project-root}/doc/openapi"
    output-file: "{service-name}.openapi.yaml"
    file-type: yaml
    new-line: lf
