[global]
error_log = /proc/self/fd/2
pid = /tmp/php-fpm.pid
process_control_timeout = 100s
[www]
listen = 127.0.0.1:9000
pm = dynamic
pm.max_children = 10
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3
clear_env = no
catch_workers_output = yes
decorate_workers_output = no
access.log = /proc/self/fd/2
request_terminate_timeout = 95s
php_admin_flag[log_errors] = on
php_admin_value[error_log] = /proc/self/fd/2
