<?php

declare(strict_types=1);

namespace Application\Providers\Wiki;

use Illuminate\Support\ServiceProvider;
use Source\Wiki\Image\Application\UseCase\Command\ApproveImage\ApproveImage;
use Source\Wiki\Image\Application\UseCase\Command\ApproveImage\ApproveImageInterface;
use Source\Wiki\Image\Application\UseCase\Command\ApproveImageHideRequest\ApproveImageHideRequest;
use Source\Wiki\Image\Application\UseCase\Command\ApproveImageHideRequest\ApproveImageHideRequestInterface;
use Source\Wiki\Image\Application\UseCase\Command\DeleteImage\DeleteImage;
use Source\Wiki\Image\Application\UseCase\Command\DeleteImage\DeleteImageInterface;
use Source\Wiki\Image\Application\UseCase\Command\RejectImage\RejectImage;
use Source\Wiki\Image\Application\UseCase\Command\RejectImage\RejectImageInterface;
use Source\Wiki\Image\Application\UseCase\Command\RejectImageHideRequest\RejectImageHideRequest;
use Source\Wiki\Image\Application\UseCase\Command\RejectImageHideRequest\RejectImageHideRequestInterface;
use Source\Wiki\Image\Application\UseCase\Command\RequestImageHide\RequestImageHide;
use Source\Wiki\Image\Application\UseCase\Command\RequestImageHide\RequestImageHideInterface;
use Source\Wiki\Image\Application\UseCase\Command\UnhideImage\UnhideImage;
use Source\Wiki\Image\Application\UseCase\Command\UnhideImage\UnhideImageInterface;
use Source\Wiki\Image\Application\UseCase\Command\UploadImage\UploadImage;
use Source\Wiki\Image\Application\UseCase\Command\UploadImage\UploadImageInterface;
use Source\Wiki\OfficialCertification\Application\UseCase\Command\ApproveCertification\ApproveCertification;
use Source\Wiki\OfficialCertification\Application\UseCase\Command\ApproveCertification\ApproveCertificationInterface;
use Source\Wiki\OfficialCertification\Application\UseCase\Command\RejectCertification\RejectCertification;
use Source\Wiki\OfficialCertification\Application\UseCase\Command\RejectCertification\RejectCertificationInterface;
use Source\Wiki\OfficialCertification\Application\UseCase\Command\RequestCertification\RequestCertification;
use Source\Wiki\OfficialCertification\Application\UseCase\Command\RequestCertification\RequestCertificationInterface;
use Source\Wiki\Principal\Application\UseCase\Command\AddPrincipalToPrincipalGroup\AddPrincipalToPrincipalGroup;
use Source\Wiki\Principal\Application\UseCase\Command\AddPrincipalToPrincipalGroup\AddPrincipalToPrincipalGroupInterface;
use Source\Wiki\Principal\Application\UseCase\Command\AttachPolicyToRole\AttachPolicyToRole;
use Source\Wiki\Principal\Application\UseCase\Command\AttachPolicyToRole\AttachPolicyToRoleInterface;
use Source\Wiki\Principal\Application\UseCase\Command\AttachRoleToPrincipalGroup\AttachRoleToPrincipalGroup;
use Source\Wiki\Principal\Application\UseCase\Command\AttachRoleToPrincipalGroup\AttachRoleToPrincipalGroupInterface;
use Source\Wiki\Principal\Application\UseCase\Command\CreatePolicy\CreatePolicy;
use Source\Wiki\Principal\Application\UseCase\Command\CreatePolicy\CreatePolicyInterface;
use Source\Wiki\Principal\Application\UseCase\Command\CreatePrincipal\CreatePrincipal;
use Source\Wiki\Principal\Application\UseCase\Command\CreatePrincipal\CreatePrincipalInterface;
use Source\Wiki\Principal\Application\UseCase\Command\CreatePrincipalGroup\CreatePrincipalGroup;
use Source\Wiki\Principal\Application\UseCase\Command\CreatePrincipalGroup\CreatePrincipalGroupInterface;
use Source\Wiki\Principal\Application\UseCase\Command\CreateRole\CreateRole;
use Source\Wiki\Principal\Application\UseCase\Command\CreateRole\CreateRoleInterface;
use Source\Wiki\Principal\Application\UseCase\Command\DeletePolicy\DeletePolicy;
use Source\Wiki\Principal\Application\UseCase\Command\DeletePolicy\DeletePolicyInterface;
use Source\Wiki\Principal\Application\UseCase\Command\DeletePrincipalGroup\DeletePrincipalGroup;
use Source\Wiki\Principal\Application\UseCase\Command\DeletePrincipalGroup\DeletePrincipalGroupInterface;
use Source\Wiki\Principal\Application\UseCase\Command\DeleteRole\DeleteRole;
use Source\Wiki\Principal\Application\UseCase\Command\DeleteRole\DeleteRoleInterface;
use Source\Wiki\Principal\Application\UseCase\Command\DetachPolicyFromRole\DetachPolicyFromRole;
use Source\Wiki\Principal\Application\UseCase\Command\DetachPolicyFromRole\DetachPolicyFromRoleInterface;
use Source\Wiki\Principal\Application\UseCase\Command\DetachRoleFromPrincipalGroup\DetachRoleFromPrincipalGroup;
use Source\Wiki\Principal\Application\UseCase\Command\DetachRoleFromPrincipalGroup\DetachRoleFromPrincipalGroupInterface;
use Source\Wiki\Principal\Application\UseCase\Command\RemovePrincipalFromPrincipalGroup\RemovePrincipalFromPrincipalGroup;
use Source\Wiki\Principal\Application\UseCase\Command\RemovePrincipalFromPrincipalGroup\RemovePrincipalFromPrincipalGroupInterface;
use Source\Wiki\Wiki\Application\UseCase\Command\ApproveWiki\ApproveWiki;
use Source\Wiki\Wiki\Application\UseCase\Command\ApproveWiki\ApproveWikiInterface;
use Source\Wiki\Wiki\Application\UseCase\Command\AutoCreateWiki\AutoCreateWiki;
use Source\Wiki\Wiki\Application\UseCase\Command\AutoCreateWiki\AutoCreateWikiInterface;
use Source\Wiki\Wiki\Application\UseCase\Command\CreateWiki\CreateWiki;
use Source\Wiki\Wiki\Application\UseCase\Command\CreateWiki\CreateWikiInterface;
use Source\Wiki\Wiki\Application\UseCase\Command\EditWiki\EditWiki;
use Source\Wiki\Wiki\Application\UseCase\Command\EditWiki\EditWikiInterface;
use Source\Wiki\Wiki\Application\UseCase\Command\MergeWiki\MergeWiki;
use Source\Wiki\Wiki\Application\UseCase\Command\MergeWiki\MergeWikiInterface;
use Source\Wiki\Wiki\Application\UseCase\Command\PublishWiki\PublishWiki;
use Source\Wiki\Wiki\Application\UseCase\Command\PublishWiki\PublishWikiInterface;
use Source\Wiki\Wiki\Application\UseCase\Command\RejectWiki\RejectWiki;
use Source\Wiki\Wiki\Application\UseCase\Command\RejectWiki\RejectWikiInterface;
use Source\Wiki\Wiki\Application\UseCase\Command\RollbackWiki\RollbackWiki;
use Source\Wiki\Wiki\Application\UseCase\Command\RollbackWiki\RollbackWikiInterface;
use Source\Wiki\Wiki\Application\UseCase\Command\SubmitWiki\SubmitWiki;
use Source\Wiki\Wiki\Application\UseCase\Command\SubmitWiki\SubmitWikiInterface;
use Source\Wiki\Wiki\Application\UseCase\Command\TranslateWiki\TranslateWiki;
use Source\Wiki\Wiki\Application\UseCase\Command\TranslateWiki\TranslateWikiInterface;
use Source\Wiki\Wiki\Application\UseCase\Query\GetGroupDraftWiki\GetGroupDraftWikiInterface;
use Source\Wiki\Wiki\Application\UseCase\Query\GetTalentDraftWiki\GetTalentDraftWikiInterface;
use Source\Wiki\Wiki\Infrastructure\Query\GetGroupDraftWiki;
use Source\Wiki\Wiki\Infrastructure\Query\GetTalentDraftWiki;

class UseCaseServiceProvider extends ServiceProvider
{
    public function boot(): void
    {
        $this->app->singleton(CreatePrincipalInterface::class, CreatePrincipal::class);
        $this->app->singleton(CreatePrincipalGroupInterface::class, CreatePrincipalGroup::class);
        $this->app->singleton(DeletePrincipalGroupInterface::class, DeletePrincipalGroup::class);
        $this->app->singleton(CreatePolicyInterface::class, CreatePolicy::class);
        $this->app->singleton(DeletePolicyInterface::class, DeletePolicy::class);
        $this->app->singleton(CreateRoleInterface::class, CreateRole::class);
        $this->app->singleton(DeleteRoleInterface::class, DeleteRole::class);
        $this->app->singleton(AttachPolicyToRoleInterface::class, AttachPolicyToRole::class);
        $this->app->singleton(DetachPolicyFromRoleInterface::class, DetachPolicyFromRole::class);
        $this->app->singleton(AddPrincipalToPrincipalGroupInterface::class, AddPrincipalToPrincipalGroup::class);
        $this->app->singleton(RemovePrincipalFromPrincipalGroupInterface::class, RemovePrincipalFromPrincipalGroup::class);
        $this->app->singleton(AttachRoleToPrincipalGroupInterface::class, AttachRoleToPrincipalGroup::class);
        $this->app->singleton(DetachRoleFromPrincipalGroupInterface::class, DetachRoleFromPrincipalGroup::class);
        $this->app->singleton(RequestCertificationInterface::class, RequestCertification::class);
        $this->app->singleton(ApproveCertificationInterface::class, ApproveCertification::class);
        $this->app->singleton(RejectCertificationInterface::class, RejectCertification::class);
        $this->app->singleton(UploadImageInterface::class, UploadImage::class);
        $this->app->singleton(ApproveImageInterface::class, ApproveImage::class);
        $this->app->singleton(RejectImageInterface::class, RejectImage::class);
        $this->app->singleton(DeleteImageInterface::class, DeleteImage::class);
        $this->app->singleton(UnhideImageInterface::class, UnhideImage::class);
        $this->app->singleton(RequestImageHideInterface::class, RequestImageHide::class);
        $this->app->singleton(ApproveImageHideRequestInterface::class, ApproveImageHideRequest::class);
        $this->app->singleton(RejectImageHideRequestInterface::class, RejectImageHideRequest::class);
        $this->app->singleton(CreateWikiInterface::class, CreateWiki::class);
        $this->app->singleton(AutoCreateWikiInterface::class, AutoCreateWiki::class);
        $this->app->singleton(EditWikiInterface::class, EditWiki::class);
        $this->app->singleton(MergeWikiInterface::class, MergeWiki::class);
        $this->app->singleton(SubmitWikiInterface::class, SubmitWiki::class);
        $this->app->singleton(ApproveWikiInterface::class, ApproveWiki::class);
        $this->app->singleton(RejectWikiInterface::class, RejectWiki::class);
        $this->app->singleton(PublishWikiInterface::class, PublishWiki::class);
        $this->app->singleton(RollbackWikiInterface::class, RollbackWiki::class);
        $this->app->singleton(TranslateWikiInterface::class, TranslateWiki::class);
        $this->app->singleton(GetGroupDraftWikiInterface::class, GetGroupDraftWiki::class);
        $this->app->singleton(GetTalentDraftWikiInterface::class, GetTalentDraftWiki::class);
    }
}
